Bash improvements

diff --git a/roles/zfs_autobackup/templates/zfs_autosnapshot.sh.j2 b/roles/zfs_autobackup/templates/zfs_autosnapshot.sh.j2
--- a/roles/zfs_autobackup/templates/zfs_autosnapshot.sh.j2
+++ b/roles/zfs_autobackup/templates/zfs_autosnapshot.sh.j2
@@ -2,27 +2,18 @@
 # shellcheck source=../../bash/files/functions.sh
 source /usr/local/lib/functions.sh
 
-PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+f_require_root
 
-failed=0
+# create local snapshots
+f_rescue zfs_backup_local
 
-rescue() {
-  set +e
-  "$@"
-  retval=$?
-  set -e
+# backup snapshot to other server
+f_rescue zfs_backup_onsite "{{ external_ips[zfs_autobackup_source_host] }}" "{{ zfs_autobackup_dest_dataset }}"
 
-  if [ $retval -ne 0 ]; then
-    failed=1
-  fi
-}
-
-rescue zfs_backup_local
-
-rescue zfs_backup_onsite "{{ external_ips[zfs_autobackup_source_host] }}" "{{ zfs_autobackup_dest_dataset }}"
-
+# sync each dataset to offsite synology
 for dataset in $(zfs get 'autobackup:bak' -t filesystem -H -s local -o name,value | awk -v FS='\t' '$2=="true" {print $1}'); do
-  rescue zfs_backup_offsite "{{ (wireguard_peers|selectattr('name', 'eq', 'bunk')|first).address }}" "$dataset"
+  f_rescue zfs_backup_offsite "{{ (wireguard_peers|selectattr('name', 'eq', 'bunk')|first).address }}" "$dataset"
 done
 
-exit $failed
+# fail if any of the above failed
+exit $f_failed
